// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmGO6MpZGxcdeN2Yohdm4EGu61CAbPe6o',
    appId: '1:566710749077:web:ada8c42bfa17a349e3989c',
    messagingSenderId: '566710749077',
    projectId: 'sample-app-96c54',
    authDomain: 'sample-app-96c54.firebaseapp.com',
    storageBucket: 'sample-app-96c54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1hqMPpCa-rlZMG9xwoFrZ8nO14W_H-wg',
    appId: '1:566710749077:android:9c92e20f41bf8d8ae3989c',
    messagingSenderId: '566710749077',
    projectId: 'sample-app-96c54',
    storageBucket: 'sample-app-96c54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzjTTx1_m5L9EzcFPZ0BO6BhA-HgRAH7E',
    appId: '1:566710749077:ios:4cc553d05ad16651e3989c',
    messagingSenderId: '566710749077',
    projectId: 'sample-app-96c54',
    storageBucket: 'sample-app-96c54.appspot.com',
    iosBundleId: 'com.example.flu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzjTTx1_m5L9EzcFPZ0BO6BhA-HgRAH7E',
    appId: '1:566710749077:ios:f1d9ba3188c2f8d1e3989c',
    messagingSenderId: '566710749077',
    projectId: 'sample-app-96c54',
    storageBucket: 'sample-app-96c54.appspot.com',
    iosBundleId: 'com.example.flu.RunnerTests',
  );
}
